### ISSUE TITLE
branches for the child node

### ISSUE THREAD

**Issue by drhmoosavi** [mw201608/sunburst.shiny#1]
Hi
Thank you for making this very interesting package.
I am trying to make a sunburst plot based from the text file below, but i cannot figure out how to add branches to child node based on the L3 column in the data.
Appreciated if you could help me with that. Thanks.
[MMdata - Copy.txt](https://github.com/mw201608/sunburst.shiny/files/3680158/MMdata.-.Copy.txt)

**Comment by mw201608** [comment]
Hi,

Sorry for the late response as I did not get notification from Github about opening issue. If I understand your data clearly, each row is a path L1 -> L2 -> L3? If that is the case, you need reformat the data into two columns by stacking L2 -> L3 after L1 -> L2 as attached so that it can be used by my tool sunburst.shiny.

[MMdata.txt](https://github.com/mw201608/sunburst.shiny/files/3927920/MMdata.txt)

**Comment by mw201608** [comment]
Closed since no follow-up from op.
